name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]         # change if your default branch is different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare root for publish
        run: |
          # prevent Jekyll from hiding folders like /images or files starting with underscore
          touch .nojekyll
          echo "Publishing repo root:"
          ls -la

      - name: Upload artifact (root)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .               # publish the repo root

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
