name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]    # change if your default branch is different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Create a root index.html that redirects to /game/
      - name: Create root redirect
        run: |
          cat > index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=game/">
          <link rel="canonical" href="game/">
          <title>Redirecting…</title>
          If you are not redirected automatically, <a href="game/">open the game</a>.
          HTML

      # Avoid Jekyll processing just in case
      - name: Disable Jekyll
        run: touch .nojekyll

      # Upload exactly what the site needs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            game
            images
            sounds
            index.html
            .nojekyll

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
